FROM ubuntu:22.04

RUN groupadd -r steampipe && useradd -r -g steampipe steampipe
RUN apt-get update && apt-get install -y curl wget ca-certificates && rm -rf /var/lib/apt/lists/*
RUN /bin/sh -c "$(curl -fsSL https://steampipe.io/install/steampipe.sh)"

USER steampipe
WORKDIR /home/steampipe
ENTRYPOINT ["/usr/local/bin/steampipe"]
