FROM docker.io/alpine

RUN apk update && apk upgrade && apk add --no-cache curl wget
RUN /bin/sh -c "$(curl -fsSL https://steampipe.io/install/steampipe.sh)"

RUN adduser -D steampipe
USER steampipe
WORKDIR /home/steampipe

RUN steampipe plugin install aws

ENTRYPOINT ["steampipe"]
