# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  isDesktop = builtins.readDir /sys/class/power_supply == {};
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.extraModprobeConfig =
    if builtins.hasAttr "hid_apple" (builtins.readDir /sys/module)
    then ''
      options hid_apple fnmode=2
      options hid_apple swap_opt_cmd=1
      options hid_apple swap_fn_leftctrl=1
    ''
    else "";

  boot.loader.efi.canTouchEfiVariables = true;

  boot.loader.systemd-boot.enable = isDesktop;

  boot.loader.grub =
    if isDesktop
    then {enable = false;}
    else {
      enable = true;
      version = 2;
      device = "nodev";
      efiSupport = true;
      enableCryptodisk = true;
    };

  boot.initrd.luks.devices =
    if isDesktop
    then {}
    else {
      crypted = {
        device = "/dev/disk/by-label/crypted";
        preLVM = true;
      };
    };

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel" "wl"];
  boot.extraModulePackages = [config.boot.kernelPackages.broadcom_sta];

  fileSystems."/" = {
    device = "/dev/disk/by-label/root";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/home";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-label/swap";}];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
