# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.18.3" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.18.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.18.3.tgz";
        sha512 = "38Y8f7YUhce/K7RMwTp7m0uCumpv9hZkitCbBClqQIow1qSbCvGkcegKOXpEWCQLfWmevgRiWokZ1GkpfhbZug==";
      };
    };
    "@babel/runtime-corejs2-7.11.2" = {
      name = "_at_babel_slash_runtime-corejs2";
      packageName = "@babel/runtime-corejs2";
      version = "7.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime-corejs2/-/runtime-corejs2-7.11.2.tgz";
        sha512 = "AC/ciV28adSSpEkBglONBWq4/Lvm6GAZuxIoyVtsnUpZMl0bxLtoChEnYAkP+47KyOCayZanojtflUEUJtR/6Q==";
      };
    };
    "@emotion/is-prop-valid-0.8.8" = {
      name = "_at_emotion_slash_is-prop-valid";
      packageName = "@emotion/is-prop-valid";
      version = "0.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/is-prop-valid/-/is-prop-valid-0.8.8.tgz";
        sha512 = "u5WtneEAr5IDG2Wv65yhunPSMLIpuKsbuOktRojfrEiEvRyC85LgPMZI63cr7NUqT8ZIGdSVg8ZKGxIug4lXcA==";
      };
    };
    "@emotion/memoize-0.7.4" = {
      name = "_at_emotion_slash_memoize";
      packageName = "@emotion/memoize";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/memoize/-/memoize-0.7.4.tgz";
        sha512 = "Ja/Vfqe3HpuzRsG1oBtWTHk2PGZ7GR+2Vz5iYGelAw8dx32K0y7PjVuxK6z1nMpZOqAFsRUPCkK1YjJ56qJlgw==";
      };
    };
    "@fortawesome/fontawesome-free-6.1.1" = {
      name = "_at_fortawesome_slash_fontawesome-free";
      packageName = "@fortawesome/fontawesome-free";
      version = "6.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fortawesome/fontawesome-free/-/fontawesome-free-6.1.1.tgz";
        sha512 = "J/3yg2AIXc9wznaVqpHVX3Wa5jwKovVF0AMYSnbmcXTiL3PpRPfF58pzWucCwEiCJBp+hCNRLWClTomD8SseKg==";
      };
    };
    "@popmotion/easing-1.0.2" = {
      name = "_at_popmotion_slash_easing";
      packageName = "@popmotion/easing";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@popmotion/easing/-/easing-1.0.2.tgz";
        sha512 = "IkdW0TNmRnWTeWI7aGQIVDbKXPWHVEYdGgd5ZR4SH/Ty/61p63jCjrPxX1XrR7IGkl08bjhJROStD7j+RKgoIw==";
      };
    };
    "@popmotion/popcorn-0.4.4" = {
      name = "_at_popmotion_slash_popcorn";
      packageName = "@popmotion/popcorn";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@popmotion/popcorn/-/popcorn-0.4.4.tgz";
        sha512 = "jYO/8319fKoNLMlY4ZJPiPu8Ea8occYwRZhxpaNn/kZsK4QG2E7XFlXZMJBsTWDw7I1i0uaqyC4zn1nwEezLzg==";
      };
    };
    "@types/domhandler-2.4.1" = {
      name = "_at_types_slash_domhandler";
      packageName = "@types/domhandler";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/domhandler/-/domhandler-2.4.1.tgz";
        sha512 = "cfBw6q6tT5sa1gSPFSRKzF/xxYrrmeiut7E0TxNBObiLSBTuFEHibcfEe3waQPEDbqBsq+ql/TOniw65EyDFMA==";
      };
    };
    "@types/prop-types-15.7.3" = {
      name = "_at_types_slash_prop-types";
      packageName = "@types/prop-types";
      version = "15.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/prop-types/-/prop-types-15.7.3.tgz";
        sha512 = "KfRL3PuHmqQLOG+2tGpRO26Ctg+Cq1E01D2DMriKEATHgWLfeNDmq9e29Q9WIky0dQ3NPkd1mzYH8Lm936Z9qw==";
      };
    };
    "@types/react-16.9.43" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "16.9.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-16.9.43.tgz";
        sha512 = "PxshAFcnJqIWYpJbLPriClH53Z2WlJcVZE+NP2etUtWQs2s7yIMj3/LDKZT/5CHJ/F62iyjVCDu2H3jHEXIxSg==";
      };
    };
    "a11y-focus-store-1.0.0" = {
      name = "a11y-focus-store";
      packageName = "a11y-focus-store";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/a11y-focus-store/-/a11y-focus-store-1.0.0.tgz";
        sha1 = "ae52561cb86ae6c2904c1a4abf2e5820bf5305b0";
      };
    };
    "adler-32-1.2.0" = {
      name = "adler-32";
      packageName = "adler-32";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/adler-32/-/adler-32-1.2.0.tgz";
        sha1 = "6a3e6bf0a63900ba15652808cb15c6813d1a5f25";
      };
    };
    "adm-zip-0.5.9" = {
      name = "adm-zip";
      packageName = "adm-zip";
      version = "0.5.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/adm-zip/-/adm-zip-0.5.9.tgz";
        sha512 = "s+3fXLkeeLjZ2kLjCBwQufpI5fuN+kIGBxu6530nVQZGVol0d7Y/M88/xw9HGGUcJjKf8LutN3VPRUBq6N7Ajg==";
      };
    };
    "animation-bus-0.2.0" = {
      name = "animation-bus";
      packageName = "animation-bus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/animation-bus/-/animation-bus-0.2.0.tgz";
        sha1 = "43854c2c9463fb82c664eff0e19b9733081150fa";
      };
    };
    "aria-hidden-1.1.1" = {
      name = "aria-hidden";
      packageName = "aria-hidden";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-hidden/-/aria-hidden-1.1.1.tgz";
        sha512 = "M7zYxCcOQPOaxGHoMTKUFD2UNcVFTp9ycrdStLcTPLf8zgTXC3+YcGe+UuzSh5X1BX/0/PtS8xTNy4xyH/6xtw==";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "base64-js-1.3.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz";
        sha512 = "mLQ4i2QO1ytvGWFWmcngKO//JXAQueZvwEKtjgQFM4jIK0kU+ytMfplL8j+n5mspOfjHwoAg+9yhb7BwAHm36g==";
      };
    };
    "bootstrap-3.4.1" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-3.4.1.tgz";
        sha512 = "yN5oZVmRCwe5aKwzRj6736nSmKDX7pLYwsXiCj/EYmo16hODaBiT4En5btW/jhBF/seV+XMx3aYwukYC3A49DA==";
      };
    };
    "bowser-1.9.4" = {
      name = "bowser";
      packageName = "bowser";
      version = "1.9.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bowser/-/bowser-1.9.4.tgz";
        sha512 = "9IdMmj2KjigRq6oWhmwv1W36pDuA4STQZ8q6YO9um+x07xgYNCD3Oou+WP/3L1HNz7iqythGet3/p4wvc8AAwQ==";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "cfb-1.1.0" = {
      name = "cfb";
      packageName = "cfb";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cfb/-/cfb-1.1.0.tgz";
        sha512 = "ZqfxNGWTMKhd0a/n6YKJLq8hWbd5kR3cA4kXwUj9vVEdHlwJ09werR8gN15Z7Y1FTXqdD6dE3GGCxv4uc28raA==";
      };
    };
    "classnames-2.2.6" = {
      name = "classnames";
      packageName = "classnames";
      version = "2.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/classnames/-/classnames-2.2.6.tgz";
        sha512 = "JR/iSQOSt+LQIWwrwEzJ9uk0xfN3mTVYMwt1Ir5mUcSN6pU+V4zQFFaJsclJbPuAUQH+yfWef6tm7l1quW3C8Q==";
      };
    };
    "clsx-1.2.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-1.2.1.tgz";
        sha512 = "EcR6r5a8bj6pu3ycsa/E/cKVGuTgZJZdsyUYHOksG/UHIiKfjxzRxYJpyVBwYaQeOvghal9fcc4PidlgzugAQg==";
      };
    };
    "codepage-1.3.8" = {
      name = "codepage";
      packageName = "codepage";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/codepage/-/codepage-1.3.8.tgz";
        sha1 = "4f2e5d7c0975de28f88498058dcb5afcab6a5f71";
      };
    };
    "colors-0.6.2" = {
      name = "colors";
      packageName = "colors";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-0.6.2.tgz";
        sha1 = "2423fe6678ac0c5dae8852e5d0e5be08c997abcc";
      };
    };
    "commander-2.20.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.0.tgz";
        sha512 = "7j2y+40w61zy6YC2iRNpUe/NwhNyoXrYpHMrSunaMG64nRnaf96zO/KMQR4OyN/UnE5KLyEBnKHd4aG3rskjpQ==";
      };
    };
    "compute-scroll-into-view-1.0.16" = {
      name = "compute-scroll-into-view";
      packageName = "compute-scroll-into-view";
      version = "1.0.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/compute-scroll-into-view/-/compute-scroll-into-view-1.0.16.tgz";
        sha512 = "a85LHKY81oQnikatZYA90pufpZ6sQx++BoCxOEMsjpZx+ZnaKGQnCyCehTRr/1p9GBIAHTjcU9k71kSYWloLiQ==";
      };
    };
    "concat-stream-2.0.0" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-2.0.0.tgz";
        sha512 = "MWufYdFw53ccGjCA+Ol7XJYpAlW6/prSMzuPOTRnJGcGzuhLn4Scrz7qf6o8bROZ514ltazcIFJZevcfbo0x7A==";
      };
    };
    "conf-1.4.0" = {
      name = "conf";
      packageName = "conf";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/conf/-/conf-1.4.0.tgz";
        sha512 = "bzlVWS2THbMetHqXKB8ypsXN4DQ/1qopGwNJi1eYbpwesJcd86FBjFciCQX/YwAhp9bM7NVnPFqZ5LpV7gP0Dg==";
      };
    };
    "core-js-1.2.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz";
        sha1 = "652294c14651db28fa93bd2d5ff2983a4f08c636";
      };
    };
    "core-js-2.6.12" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.6.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.6.12.tgz";
        sha512 = "Kb2wC0fvsWfQrgk8HU5lW6U/Lcs8+9aaYcy4ZFc6DDlo4nZ7n70dEgE5rtR0oG6ufKDUnrwfWL1mXR5ljDatrQ==";
      };
    };
    "crc-32-1.2.0" = {
      name = "crc-32";
      packageName = "crc-32";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc-32/-/crc-32-1.2.0.tgz";
        sha512 = "1uBwHxF+Y/4yF5G48fwnKq6QsIXheor3ZLPT80yGBV1oEUwpPojlEhQbWKVw1VwcTQyMGHK1/XMmTjmlsmTTGA==";
      };
    };
    "create-react-context-0.3.0" = {
      name = "create-react-context";
      packageName = "create-react-context";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-react-context/-/create-react-context-0.3.0.tgz";
        sha512 = "dNldIoSuNSvlTJ7slIKC/ZFGKexBMBrrcc+TTe1NdmROnaASuLPvqpwj9v4XS4uXZ8+YPu0sNmShX2rXI5LNsw==";
      };
    };
    "cross-env-7.0.3" = {
      name = "cross-env";
      packageName = "cross-env";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-env/-/cross-env-7.0.3.tgz";
        sha512 = "+/HKd6EgcQCJGh2PSjZuUitQBQynKor4wrFbRg4DtAgS1aWO+gU52xpH7M9ScGgXSYmAVS9bIJ8EzuaGw0oNAw==";
      };
    };
    "cross-spawn-7.0.1" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.1.tgz";
        sha512 = "u7v4o84SwFpD32Z8IIcPZ6z1/ie24O6RU3RbtL5Y316l3KuHVPx9ItBgWQ6VlfAFnRnTtMUrsQ9MUUTuEZjogg==";
      };
    };
    "css-in-js-utils-2.0.1" = {
      name = "css-in-js-utils";
      packageName = "css-in-js-utils";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-in-js-utils/-/css-in-js-utils-2.0.1.tgz";
        sha512 = "PJF0SpJT+WdbVVt0AOYp9C8GnuruRlL/UFW7932nLWmFLQTaWEzTBQEx7/hn4BuV+WON75iAViSUJLiU3PKbpA==";
      };
    };
    "csstype-2.6.11" = {
      name = "csstype";
      packageName = "csstype";
      version = "2.6.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-2.6.11.tgz";
        sha512 = "l8YyEC9NBkSm783PFTvh0FmJy7s5pFKrDp49ZL7zBGX3fWkO+N4EEyan1qqp8cwPLDcD0OSdyY6hAMoxp34JFw==";
      };
    };
    "csstype-3.0.10" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.0.10.tgz";
        sha512 = "2u44ZG2OcNUO9HDp/Jl8C07x6pU/eTR3ncV91SiK3dhG9TWvRVsCoJw14Ckx5DgWkzGA3waZWO3d7pgqpUI/XA==";
      };
    };
    "dagre-0.7.4" = {
      name = "dagre";
      packageName = "dagre";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/dagre/-/dagre-0.7.4.tgz";
        sha512 = "XvkbOx1bjJABBaE2WKSAB29rOT96M3fpq1C1n/hBLSNzwrPi06LelkU4OFA+s25Ua5yhsQvhp7+JgDdC//pM8A==";
      };
    };
    "dagre-0.8.5" = {
      name = "dagre";
      packageName = "dagre";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/dagre/-/dagre-0.8.5.tgz";
        sha512 = "/aTqmnRta7x7MCCpExk7HQL2O4owCT2h8NT//9I1OQ9vt29Pa0BzSAkR5lwFUcQ7491yVi/3CXU9jQ5o0Mn2Sw==";
      };
    };
    "deep-equal-1.1.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.1.1.tgz";
        sha512 = "yd9c5AdiqVcR+JjcwUQb9DkhJc8ngNr0MahEBGvDiJw8puWab2yZlh+nkasOnZP+EGTAP6rRp2JzJhJZzvNF8g==";
      };
    };
    "define-properties-1.1.4" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.4.tgz";
        sha512 = "uckOqKcfaVvtBdsVkdPv3XjveQJsNQqmhXgRi8uhvWWuPYZCNlzT8qAyblUgNoXdHdjMTzAqeGjAoli8f+bzPA==";
      };
    };
    "detect-node-2.0.4" = {
      name = "detect-node";
      packageName = "detect-node";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-node/-/detect-node-2.0.4.tgz";
        sha512 = "ZIzRpLJrOj7jjP2miAtgqIfmzbxa4ZOr5jJc601zklsfEx9oTzmmj2nVpIPRpNlRTIh8lc1kyViIY7BWSGNmKw==";
      };
    };
    "dom-helpers-3.4.0" = {
      name = "dom-helpers";
      packageName = "dom-helpers";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-helpers/-/dom-helpers-3.4.0.tgz";
        sha512 = "LnuPJ+dwqKDIyotW1VzmOZ5TONUN7CwkCR5hrgawTUbkBGYdeoNLZo6nNfGkCrjtE1nXXaj7iMMpDa8/d9WoIA==";
      };
    };
    "dom-helpers-5.2.1" = {
      name = "dom-helpers";
      packageName = "dom-helpers";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-helpers/-/dom-helpers-5.2.1.tgz";
        sha512 = "nRCa7CK3VTrM2NmGkIy4cbK7IZlgBE/PYMn55rrXefr5xXDP0LdtfPnblFDoVdcAfslJ7or6iqAUnx0CCGIWQA==";
      };
    };
    "dom-serializer-0.2.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.2.2.tgz";
        sha512 = "2/xPb3ORsQ42nHYiSunXkDjPLBaEj/xTwUO4B7XCZQTRk7EBtTOPaygh10YAAh2OI1Qrp6NWfpAhzswj0ydt9g==";
      };
    };
    "domelementtype-1.3.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.1.tgz";
        sha512 = "BSKB+TSpMpFI/HOxCNr1O8aMOTZ8hT3pM3GQ0w/mWRmkhEDSFJkkyzz4XQsBV44BChwGkrDfMyjVD0eA2aFV3w==";
      };
    };
    "domelementtype-2.0.1" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.0.1.tgz";
        sha512 = "5HOHUDsYZWV8FGWN0Njbr/Rn7f/eWSQi1v7+HsUVwXgn8nWWlL64zKDkS0n8ZmQ3mlWOMuXOnR+7Nx/5tMO5AQ==";
      };
    };
    "domhandler-2.4.2" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.4.2.tgz";
        sha512 = "JiK04h0Ht5u/80fdLMCEmV4zkNh2BcoMFBmZ/91WtYZ8qVXSKjiw7fXMgFPnHcSZgOo3XdinHvmnDUeMf5R4wA==";
      };
    };
    "domutils-1.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.7.0.tgz";
        sha512 = "Lgd2XcJ/NjEw+7tFvfKxOzCYKZsdct5lczQ2ZaQY8Djz7pfAD3Gbp8ySJWtreII/vDlMVmxwa6pHmdxIYgttDg==";
      };
    };
    "dot-prop-4.2.1" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-4.2.1.tgz";
        sha512 = "l0p4+mIuJIua0mhxGoh4a+iNL9bmeK5DvnSVQa6T0OhrVmaEa1XScX5Etc673FePCJOArq/4Pa2cLGODUWTPOQ==";
      };
    };
    "electron-store-1.3.0" = {
      name = "electron-store";
      packageName = "electron-store";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-store/-/electron-store-1.3.0.tgz";
        sha512 = "r1Pdl5MwpiCxgbsl0qnwv/GABO5+J/JTO16+KyqL+bOITIk9o3cq3Sw69uO9NgPkpfcKeEwxtJFbtbiBlGTiDA==";
      };
    };
    "encoding-0.1.13" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz";
        sha512 = "ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==";
      };
    };
    "entities-1.1.2" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.2.tgz";
        sha512 = "f2LZMYl1Fzu7YSBKg+RoROelpOaNrcGmE9AZubeDfrCEia483oW4MI4VyFd5VNHIgQ/7qm1I0wUHK1eJnn2y2w==";
      };
    };
    "entities-2.0.3" = {
      name = "entities";
      packageName = "entities";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.0.3.tgz";
        sha512 = "MyoZ0jgnLvB2X3Lg5HqpFmn1kybDiIfEQmKzTb5apr51Rb+T3KdmMiqa70T+bhGnyv7bQ6WMj2QMHpGMmlrUYQ==";
      };
    };
    "env-paths-1.0.0" = {
      name = "env-paths";
      packageName = "env-paths";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/env-paths/-/env-paths-1.0.0.tgz";
        sha1 = "4168133b42bb05c38a35b1ae4397c8298ab369e0";
      };
    };
    "es-abstract-1.20.1" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.20.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.20.1.tgz";
        sha512 = "WEm2oBhfoI2sImeM4OF2zE2V3BYdSF+KnSi9Sidz51fQHd7+JuF8Xgcj9/0o+OWeIeIS/MiuNnlruQrJf16GQA==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "eventemitter2-6.4.6" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "6.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-6.4.6.tgz";
        sha512 = "OHqo4wbHX5VbvlbB6o6eDwhYmiTjrpWACjF8Pmof/GTD6rdBNdZFNck3xlhqOiQFGCOoq3uzHvA0cQpFHIGVAQ==";
      };
    };
    "exit-on-epipe-1.0.1" = {
      name = "exit-on-epipe";
      packageName = "exit-on-epipe";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit-on-epipe/-/exit-on-epipe-1.0.1.tgz";
        sha512 = "h2z5mrROTxce56S+pnvAV890uu7ls7f1kEvVGJbw1OlFH3/mlJ5bkXu0KRyW94v37zzHPiUd55iLn3DA7TjWpw==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fbjs-0.8.18" = {
      name = "fbjs";
      packageName = "fbjs";
      version = "0.8.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/fbjs/-/fbjs-0.8.18.tgz";
        sha512 = "EQaWFK+fEPSoibjNy8IxUtaFOMXcWsY0JaVrQoZR9zC8N2Ygf9iDITPWjUTVIax95b6I742JFLqASHfsag/vKA==";
      };
    };
    "file-type-10.11.0" = {
      name = "file-type";
      packageName = "file-type";
      version = "10.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-10.11.0.tgz";
        sha512 = "uzk64HRpUZyTGZtVuvrjP0FYxzQrBf4rojot6J65YMEbwBLB0CWm0CLojVpwpmFmxcE/lkvYICgfcGozbBq6rw==";
      };
    };
    "find-up-2.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-2.1.0.tgz";
        sha1 = "45d1b7e506c717ddd482775a2b77920a3c0c57a7";
      };
    };
    "focus-lock-0.7.0" = {
      name = "focus-lock";
      packageName = "focus-lock";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/focus-lock/-/focus-lock-0.7.0.tgz";
        sha512 = "LI7v2mH02R55SekHYdv9pRHR9RajVNyIJ2N5IEkWbg7FT5ZmJ9Hw4mWxHeEUcd+dJo0QmzztHvDvWcc7prVFsw==";
      };
    };
    "fontfaceobserver-2.3.0" = {
      name = "fontfaceobserver";
      packageName = "fontfaceobserver";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fontfaceobserver/-/fontfaceobserver-2.3.0.tgz";
        sha512 = "6FPvD/IVyT4ZlNe7Wcn5Fb/4ChigpucKYSvD6a+0iMoLn2inpo711eyIcKjmDtE5XNcgAkSH9uN/nfAeZzHEfg==";
      };
    };
    "frac-0.3.1" = {
      name = "frac";
      packageName = "frac";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/frac/-/frac-0.3.1.tgz";
        sha1 = "577677b7fdcbe6faf7c461f1801d34137cda4354";
      };
    };
    "framer-motion-1.11.1" = {
      name = "framer-motion";
      packageName = "framer-motion";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/framer-motion/-/framer-motion-1.11.1.tgz";
        sha512 = "CP6aYLPSivAWkq9UoSurefHBggxG85IT8ObYyWYkcZppgtjHzpwRzhaA8P0ljMGRqtcpeQAIybiGgPioBPlOSw==";
      };
    };
    "framesync-4.0.4" = {
      name = "framesync";
      packageName = "framesync";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/framesync/-/framesync-4.0.4.tgz";
        sha512 = "mdP0WvVHe0/qA62KG2LFUAOiWLng5GLpscRlwzBxu2VXOp6B8hNs5C5XlFigsMgrfDrr2YbqTsgdWZTc4RXRMQ==";
      };
    };
    "fscreen-1.0.2" = {
      name = "fscreen";
      packageName = "fscreen";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fscreen/-/fscreen-1.0.2.tgz";
        sha1 = "c4c51d96d819d75a19d728e0df445f9be9bb984f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "function.prototype.name-1.1.5" = {
      name = "function.prototype.name";
      packageName = "function.prototype.name";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/function.prototype.name/-/function.prototype.name-1.1.5.tgz";
        sha512 = "uN7m/BzVKQnCUF/iW8jYea67v++2u7m5UgENbHRtdDVclOUP+FMPlCNdmk0h/ysGyo2tavMJEDqJAkJdRa1vMA==";
      };
    };
    "functions-have-names-1.2.3" = {
      name = "functions-have-names";
      packageName = "functions-have-names";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/functions-have-names/-/functions-have-names-1.2.3.tgz";
        sha512 = "xckBUXyTIqT97tq2x2AMb+g163b5JFysYk0x4qxNFwbfQkmNZoiRHb6sPzI9/QV33WeuvVYBUIiD4NzNIyqaRQ==";
      };
    };
    "get-intrinsic-1.1.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.1.1.tgz";
        sha512 = "kWZrnVM42QCiEA2Ig1bG8zjoIMOgxWwYCEeNdwY6Tv/cOSeGpcoX4pXHfKUxNKVoArnrEr2e9srnAxxGIraS9Q==";
      };
    };
    "get-nonce-1.0.1" = {
      name = "get-nonce";
      packageName = "get-nonce";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-nonce/-/get-nonce-1.0.1.tgz";
        sha512 = "FJhYRoDaiatfEkUK8HKlicmu/3SGFD51q3itKDGoSTysQJBnfOcxU5GxnhE1E6soB76MbT0MBtnKJuXyAx+96Q==";
      };
    };
    "get-prefix-1.0.0" = {
      name = "get-prefix";
      packageName = "get-prefix";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-prefix/-/get-prefix-1.0.0.tgz";
        sha1 = "0d305448a4e3176f9c277175b14e16dbe6fba0b5";
      };
    };
    "get-symbol-description-1.0.0" = {
      name = "get-symbol-description";
      packageName = "get-symbol-description";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-symbol-description/-/get-symbol-description-1.0.0.tgz";
        sha512 = "2EmdH1YvIQiZpltCNgkuiUnyukzxM/R6NDJX31Ke3BG1Nq5b0S2PhX59UKi9vZpPDQVdqn+1IcaAwnzTT5vCjw==";
      };
    };
    "glam-5.0.1" = {
      name = "glam";
      packageName = "glam";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/glam/-/glam-5.0.1.tgz";
        sha512 = "NCnYcPpefXJMH30LaUfKKP3BkpipI9jkeOvzMZAd76cuDxfKmQRBvgQ1LxXRj9IRZVAwl0K3WQvbw+tiyK2pcw==";
      };
    };
    "graceful-fs-4.1.15" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.15.tgz";
        sha512 = "6uHUhOPEBgQ24HM+r6b/QwWfZq+yiFcipKFrOFiBEnWdy5sdzYoi+pJeQaPI5qOLRFqWmAXUPQNsielzdLoecA==";
      };
    };
    "graphlib-1.0.7" = {
      name = "graphlib";
      packageName = "graphlib";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphlib/-/graphlib-1.0.7.tgz";
        sha512 = "jNb7RbqTIRyZRmcVCxGefOlGWjNdbjcT2tFj36zhnRa8yhAlOvydh9nBixfLQIqSU+DwCx47tg3ysw8NIYhpsA==";
      };
    };
    "graphlib-2.1.8" = {
      name = "graphlib";
      packageName = "graphlib";
      version = "2.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/graphlib/-/graphlib-2.1.8.tgz";
        sha512 = "jcLLfkpoVGmH7/InMC/1hIvOPSUh38oJtGhvrOFGzioE1DZ+0YW16RgmOJhHiuWTvGiJQ9Z1Ik43JvkRPRvE+A==";
      };
    };
    "gud-1.0.0" = {
      name = "gud";
      packageName = "gud";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gud/-/gud-1.0.0.tgz";
        sha512 = "zGEOVKFM5sVPPrYs7J5/hYEw2Pof8KCyOwyhG8sAF26mCAeUFAcYPu1mwB7hhpIP29zOIBaDqwuHdLp0jvZXjw==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-bigints-1.0.2" = {
      name = "has-bigints";
      packageName = "has-bigints";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-bigints/-/has-bigints-1.0.2.tgz";
        sha512 = "tSvCKtBr9lkF0Ex0aQiP9N+OpV4zi2r/Nee5VkRDbaqv35RLYMzbwQfFSZZH0kR+Rd6302UJZ2p/bJCEoR3VoQ==";
      };
    };
    "has-property-descriptors-1.0.0" = {
      name = "has-property-descriptors";
      packageName = "has-property-descriptors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-property-descriptors/-/has-property-descriptors-1.0.0.tgz";
        sha512 = "62DVLZGoiEBDHQyqG4w9xCuZ7eJEwNmJRWw2VY84Oedb7WFcA27fiEVe8oUQx9hAUJ4ekurquucTGwsyO1XGdQ==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "has-tostringtag-1.0.0" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.0.tgz";
        sha512 = "kFjcSNhnlGV1kyoGk7OXKSawH5JOb/LzUc5w9B02hOTO0dfFRjbHQKvg1d6cf3HbeUmtU9VbbV3qzZ2Teh97WQ==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "hey-listen-1.0.8" = {
      name = "hey-listen";
      packageName = "hey-listen";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/hey-listen/-/hey-listen-1.0.8.tgz";
        sha512 = "COpmrF2NOg4TBWUJ5UVyaCU2A88wEMkUPK4hNqyCkqHbxT92BbvfjoSozkAIIm6XhicGlJHhFdullInrdhwU8Q==";
      };
    };
    "html-dom-parser-0.2.3" = {
      name = "html-dom-parser";
      packageName = "html-dom-parser";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-dom-parser/-/html-dom-parser-0.2.3.tgz";
        sha512 = "GdzE63/U0IQEvcpAz0cUdYx2zQx0Ai+HWvE9TXEgwP27+SymUzKa7iB4DhjYpf2IdNLfTTOBuMS5nxeWOosSMQ==";
      };
    };
    "html-react-parser-0.10.5" = {
      name = "html-react-parser";
      packageName = "html-react-parser";
      version = "0.10.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-react-parser/-/html-react-parser-0.10.5.tgz";
        sha512 = "rtMWZ7KZjd9sO8jyIX7am0vGCIL45tCmctTnassT/BrTGeTaAZ4nQyqoGcx2v+vB8CAY+Q5PZiiV6eOiowq8dQ==";
      };
    };
    "htmlparser2-3.10.1" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.10.1.tgz";
        sha512 = "IgieNijUMbkDovyoKObU1DUhm1iwNYE/fuifEoEHfd1oZKZDaONBSkal7Y01shxsM49R4XaMdGez3WnF9UfiCQ==";
      };
    };
    "hyphenate-style-name-1.0.4" = {
      name = "hyphenate-style-name";
      packageName = "hyphenate-style-name";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hyphenate-style-name/-/hyphenate-style-name-1.0.4.tgz";
        sha512 = "ygGZLjmXfPHj+ZWh6LwbC37l43MhfztxetbFCoYTM2VjkIUpeHgSNn7QIyVFj7YQ1Wl9Cbw5sholVJPzWvC2MQ==";
      };
    };
    "iconv-lite-0.6.2" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.2.tgz";
        sha512 = "2y91h5OpQlolefMPmUlivelittSWy0rP+oYVpn6A7GwVHNE8AWzoYOBNmlwks3LobaJxgHCYZAnyNo2GgpNRNQ==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "image-size-0.8.3" = {
      name = "image-size";
      packageName = "image-size";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-size/-/image-size-0.8.3.tgz";
        sha512 = "SMtq1AJ+aqHB45c3FsB4ERK0UCiA2d3H1uq8s+8T0Pf8A3W4teyBQyaFaktH6xvZqh+npwlKU7i4fJo0r7TYTg==";
      };
    };
    "image-type-4.1.0" = {
      name = "image-type";
      packageName = "image-type";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-type/-/image-type-4.1.0.tgz";
        sha512 = "CFJMJ8QK8lJvRlTCEgarL4ro6hfDQKif2HjSvYCdQZESaIPV4v9imrf7BQHK+sQeTeNeMpWciR9hyC/g8ybXEg==";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "inline-style-parser-0.1.1" = {
      name = "inline-style-parser";
      packageName = "inline-style-parser";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-style-parser/-/inline-style-parser-0.1.1.tgz";
        sha512 = "7NXolsK4CAS5+xvdj5OMMbI962hU/wvwoxk+LWR9Ek9bVtyuuYScDN6eS0rUm6TxApFpw7CX1o4uJzcd4AyD3Q==";
      };
    };
    "inline-style-prefixer-3.0.8" = {
      name = "inline-style-prefixer";
      packageName = "inline-style-prefixer";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-style-prefixer/-/inline-style-prefixer-3.0.8.tgz";
        sha1 = "8551b8e5b4d573244e66a34b04f7d32076a2b534";
      };
    };
    "internal-slot-1.0.3" = {
      name = "internal-slot";
      packageName = "internal-slot";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/internal-slot/-/internal-slot-1.0.3.tgz";
        sha512 = "O0DB1JC/sPyZl7cIo78n5dR7eUSwwpYPiXRhTzNxZVAMUuB8vlnRFyLxdrVToks6XPLVnFfbzaVd5WLjhgg+vA==";
      };
    };
    "invariant-2.2.4" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.4.tgz";
        sha512 = "phJfQVBuaJM5raOpJjSfkiD6BpbCE4Ns//LaXl6wGYtUBY83nWS6Rf9tXm2e8VaK60JEjYldbPif/A2B1C2gNA==";
      };
    };
    "is-arguments-1.0.4" = {
      name = "is-arguments";
      packageName = "is-arguments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arguments/-/is-arguments-1.0.4.tgz";
        sha512 = "xPh0Rmt8NE65sNzvyUmWgI1tz3mKq74lGA0mL8LYZcoIzKOzDh6HmrYm3d18k60nHerC8A9Km8kYu87zfSFnLA==";
      };
    };
    "is-bigint-1.0.4" = {
      name = "is-bigint";
      packageName = "is-bigint";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-bigint/-/is-bigint-1.0.4.tgz";
        sha512 = "zB9CruMamjym81i2JZ3UMn54PKGsQzsJeo6xvN3HJJ4CAsQNB6iRutp2To77OfCNuoxspsIhzaPoO1zyCEhFOg==";
      };
    };
    "is-boolean-object-1.1.2" = {
      name = "is-boolean-object";
      packageName = "is-boolean-object";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.2.tgz";
        sha512 = "gDYaKHJmnj4aWxyj6YHyXVpdQawtVLHU5cb+eztPGczf6cjuTdwve5ZIEfgXqH4e57An1D1AKf8CZ3kYrQRqYA==";
      };
    };
    "is-callable-1.2.4" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.4.tgz";
        sha512 = "nsuwtxZfMX67Oryl9LCQ+upnC0Z0BgpwntpS89m1H/TLF0zNfzfLMV/9Wa/6MZsj0acpEjAO0KF1xT6ZdLl95w==";
      };
    };
    "is-date-object-1.0.2" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.2.tgz";
        sha512 = "USlDT524woQ08aoZFzh3/Z6ch9Y/EWXEHQ/AaRN0SkKq4t2Jw2R2339tSXmwuVoY7LLlBCbOIlx2myP/L5zk0g==";
      };
    };
    "is-negative-zero-2.0.2" = {
      name = "is-negative-zero";
      packageName = "is-negative-zero";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-negative-zero/-/is-negative-zero-2.0.2.tgz";
        sha512 = "dqJvarLawXsFbNDeJW7zAz8ItJ9cd28YufuuFzh0G8pNHjJMnY08Dv7sYX2uF5UpQOwieAeOExEYAWWfu7ZZUA==";
      };
    };
    "is-number-object-1.0.7" = {
      name = "is-number-object";
      packageName = "is-number-object";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number-object/-/is-number-object-1.0.7.tgz";
        sha512 = "k1U0IRzLMo7ZlYIfzRu23Oh6MiIFasgpb9X76eqfFZAqwH44UI4KTBvBYIZ1dSL9ZzChTB9ShHfLkR4pdW5krQ==";
      };
    };
    "is-obj-1.0.1" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-1.0.1.tgz";
        sha1 = "3e4729ac1f5fde025cd7d83a896dab9f4f67db0f";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "is-shared-array-buffer-1.0.2" = {
      name = "is-shared-array-buffer";
      packageName = "is-shared-array-buffer";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-shared-array-buffer/-/is-shared-array-buffer-1.0.2.tgz";
        sha512 = "sqN2UDu1/0y6uvXyStCOzyhAjCSlHceFoMKJW8W9EU9cvic/QdsZ0kEU93HEy3IUEFZIiH/3w+AH/UQbPHNdhA==";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "is-string-1.0.7" = {
      name = "is-string";
      packageName = "is-string";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-string/-/is-string-1.0.7.tgz";
        sha512 = "tE2UXzivje6ofPW7l23cjDOMa09gb7xlAqG6jG5ej6uPV32TlWP3NKPigtaGeHNu9fohccRYvIiZMfOOnOYUtg==";
      };
    };
    "is-symbol-1.0.3" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.3.tgz";
        sha512 = "OwijhaRSgqvhm/0ZdAcXNZt9lYdKFpcRDT5ULUuYXPoT794UNOdU+gpT6Rzo7b4V2HUl/op6GqY894AZwv9faQ==";
      };
    };
    "is-weakref-1.0.2" = {
      name = "is-weakref";
      packageName = "is-weakref";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-weakref/-/is-weakref-1.0.2.tgz";
        sha512 = "qctsuLZmIQ0+vSSMfoVvyFe2+GSEvnmZ2ezTup1SBse9+twCCeial6EEi3Nc2KFcf6+qz2FBPnjXsk8xhKSaPQ==";
      };
    };
    "is-zip-file-1.0.2" = {
      name = "is-zip-file";
      packageName = "is-zip-file";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-zip-file/-/is-zip-file-1.0.2.tgz";
        sha1 = "b05c22e17f335729e1ada858343b125a366a1792";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha1 = "4e431e92b11a9731636aa1f9c8d1ccbcfdab78df";
      };
    };
    "isomorphic-fetch-2.2.1" = {
      name = "isomorphic-fetch";
      packageName = "isomorphic-fetch";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-2.2.1.tgz";
        sha512 = "9c4TNAKYXM5PRyVcwUZrF3W09nQ+sO7+jydgs4ZGW9dhsLG2VOlISJABombdQqQRXCwuYG3sYV/puGf5rp0qmA==";
      };
    };
    "jquery-3.6.0" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.6.0.tgz";
        sha512 = "JVzAR/AjBvVt2BmYhxRCSYysDsPcssdmTFnzyLEts9qNwmjmu4JTAMYubEfwVOSwpQ1I1sKKFcxhZCI2buerfw==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "jszip-2.4.0" = {
      name = "jszip";
      packageName = "jszip";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jszip/-/jszip-2.4.0.tgz";
        sha512 = "m+yvNmYfRCaf1gr5YFT5e3fnSqLnE9McbNyRd0fNycsT0HltS19NKc18fh3Lvl/AIW/ovL6/MQ1JnfFg4G3o4A==";
      };
    };
    "keycode-2.2.0" = {
      name = "keycode";
      packageName = "keycode";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keycode/-/keycode-2.2.0.tgz";
        sha1 = "3d0af56dc7b8b8e5cba8d0a97f107204eec22b04";
      };
    };
    "linkurious-1.5.2" = {
      name = "linkurious";
      packageName = "linkurious";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkurious/-/linkurious-1.5.2.tgz";
        sha512 = "P7GAIjmVV5MnWuIo6eTsP/VEW+K4FCzTnBtGhC7T7AoAfYUNDZkjTTh6rlam+/WvPWyV9V12qCTdWjGKtPOGzA==";
      };
    };
    "locate-path-2.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-2.0.0.tgz";
        sha1 = "2b568b265eec944c6d9c0de9c3dbbbca0354cd8e";
      };
    };
    "lodash-3.10.1" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz";
        sha512 = "9mDDwqVIma6OZX79ZlDACZl8sBm0TEnkf99zV3iMA4GzkIT/9hiqP5mY0HoT1iNLCrKc/R1HByV+yJfRWVJryQ==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash.debounce-4.0.8" = {
      name = "lodash.debounce";
      packageName = "lodash.debounce";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.debounce/-/lodash.debounce-4.0.8.tgz";
        sha1 = "82d79bff30a67c4005ffd5e2515300ad9ca4d7af";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "make-dir-1.3.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-1.3.0.tgz";
        sha512 = "2w31R7SJtieJJnQtGc7RVL2StM2vGYVfqUOvUDxH6bC6aJTxPxTF0GnIgCyu7tjockiUWAYQRbxa7vKn34s5sQ==";
      };
    };
    "md5-file-4.0.0" = {
      name = "md5-file";
      packageName = "md5-file";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5-file/-/md5-file-4.0.0.tgz";
        sha512 = "UC0qFwyAjn4YdPpKaDNw6gNxRf7Mcx7jC1UGCY4boCzgvU2Aoc1mOGzTtrjjLKhM5ivsnhoKpQVxKPp+1j1qwg==";
      };
    };
    "mitt-1.1.3" = {
      name = "mitt";
      packageName = "mitt";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mitt/-/mitt-1.1.3.tgz";
        sha512 = "mUDCnVNsAi+eD6qA0HkRkwYczbLHJ49z17BGe2PYRhZL4wpZUFZGJHU7/5tmvohoma+Hdn0Vh/oJTiPEmgSruA==";
      };
    };
    "mustache-2.3.2" = {
      name = "mustache";
      packageName = "mustache";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mustache/-/mustache-2.3.2.tgz";
        sha512 = "KpMNwdQsYz3O/SBS1qJ/o3sqUJ5wSb8gb0pul8CO0S56b9Y2ALm8zCfsjPXsqGFfoNBkDwZuZIAjhsZI03gYVQ==";
      };
    };
    "neo4j-driver-4.4.6" = {
      name = "neo4j-driver";
      packageName = "neo4j-driver";
      version = "4.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/neo4j-driver/-/neo4j-driver-4.4.6.tgz";
        sha512 = "KzTEQ/PYuaVkeEuQmr8jZm0cFLlK/zAAMe3IkhxWj56Tgwn2nT2RASPrqwvyEVfk8jg6xS4U1Fx2VABmkO4cdQ==";
      };
    };
    "neo4j-driver-bolt-connection-4.4.6" = {
      name = "neo4j-driver-bolt-connection";
      packageName = "neo4j-driver-bolt-connection";
      version = "4.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/neo4j-driver-bolt-connection/-/neo4j-driver-bolt-connection-4.4.6.tgz";
        sha512 = "ZjYVwHk8oMeRtBf4j/1CmA/7t88OHl7WOiZtFnbdU3LHkfnhtrovLk7sU1zGK60f6AmaQrA9lAh1rpxwDfri5Q==";
      };
    };
    "neo4j-driver-core-4.4.6" = {
      name = "neo4j-driver-core";
      packageName = "neo4j-driver-core";
      version = "4.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/neo4j-driver-core/-/neo4j-driver-core-4.4.6.tgz";
        sha512 = "8Pc5lLeWwrxjrEGyJm8QASfguKK90i4YxB4Unz1FWV1z3xRq2xFtLhNl6PSa5Kx1VtKS5dhiwHlJArBJJEQjZA==";
      };
    };
    "node-fetch-1.7.3" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-1.7.3.tgz";
        sha512 = "NhZ4CsKx7cYm2vSrBAr2PvFOe6sWDf0UYLRqA6svUYg7+/TSfVAu49jYC4BvQ4Sms9SZgdqGBgroqfDhJdTyKQ==";
      };
    };
    "node-ratify-1.1.32" = {
      name = "node-ratify";
      packageName = "node-ratify";
      version = "1.1.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-ratify/-/node-ratify-1.1.32.tgz";
        sha1 = "3957837f2caed83bb61b9992db537d0521db2df5";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "object-inspect-1.12.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.12.0.tgz";
        sha512 = "Ho2z80bVIvJloH+YzRmpZVQe87+qASmBUKZDWgx9cu+KDrX2ZDH/3tMy+gXbZETVGs2M8YdxObOh7XAtim9Y0g==";
      };
    };
    "object-is-1.1.2" = {
      name = "object-is";
      packageName = "object-is";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-is/-/object-is-1.1.2.tgz";
        sha512 = "5lHCz+0uufF6wZ7CRFWJN3hp8Jqblpgve06U5CMQ3f//6iDjPr2PEo9MWCjEssDsa+UZEL4PkFpr+BMop6aKzQ==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.2" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.2.tgz";
        sha512 = "ixT2L5THXsApyiUPYKmW+2EHpXXe5Ii3M+f4e+aJFAHao5amFRW6J0OO6c/LU8Be47utCx2GL89hxGB6XSmKuQ==";
      };
    };
    "p-limit-1.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-1.3.0.tgz";
        sha512 = "vvcXsLAJ9Dr5rQOPk7toZQZJApBl2K4J6dANSsEuh6QI41JYcsS/qhTGa9ErIUUgK3WNQoJYvylxvjqmiqEA9Q==";
      };
    };
    "p-locate-2.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-2.0.0.tgz";
        sha1 = "20a0103b222a70c8fd39cc2e580680f3dde5ec43";
      };
    };
    "p-try-1.0.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-1.0.0.tgz";
        sha1 = "cbc79cdbaf8fd4228e13f621f2b1a237c1b207b3";
      };
    };
    "pako-0.2.9" = {
      name = "pako";
      packageName = "pako";
      version = "0.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-0.2.9.tgz";
        sha1 = "f3f7522f4ef782348da8161bad9ecfd51bf83a75";
      };
    };
    "path-exists-3.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "ce0ebeaa5f78cb18925ea7d810d7b59b010fd515";
      };
    };
    "path-key-3.1.0" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.0.tgz";
        sha512 = "8cChqz0RP6SHJkMt48FW0A7+qUOn+OsnOsVtzI59tZ8m+5bCSk7hzwET0pulwOM2YMn9J1efb07KB9l9f30SGg==";
      };
    };
    "performance-now-0.2.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-0.2.0.tgz";
        sha1 = "33ef30c5c77d4ea21c5a53869d91b56d8f2555e5";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "pify-3.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-3.0.0.tgz";
        sha1 = "e5a4acd2c101fdf3d9a4d07f0dbc4db49dd28176";
      };
    };
    "pkg-up-2.0.0" = {
      name = "pkg-up";
      packageName = "pkg-up";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkg-up/-/pkg-up-2.0.0.tgz";
        sha1 = "c819ac728059a461cab1c3889a2be3c49a004d7f";
      };
    };
    "popmotion-9.0.0-beta-8" = {
      name = "popmotion";
      packageName = "popmotion";
      version = "9.0.0-beta-8";
      src = fetchurl {
        url = "https://registry.npmjs.org/popmotion/-/popmotion-9.0.0-beta-8.tgz";
        sha512 = "6eQzqursPvnP7ePvdfPeY4wFHmS3OLzNP8rJRvmfFfEIfpFqrQgLsM50Gd9AOvGKJtYJOFknNG+dsnzCpgIdAA==";
      };
    };
    "popper.js-1.16.1" = {
      name = "popper.js";
      packageName = "popper.js";
      version = "1.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/popper.js/-/popper.js-1.16.1.tgz";
        sha512 = "Wb4p1J4zyFTbM+u6WuO4XstYx4Ky9Cewe4DWrel7B0w6VVICvPwdOpotjzcf6eD8TsckVnIMNONQyPIUFOUbCQ==";
      };
    };
    "printj-1.1.2" = {
      name = "printj";
      packageName = "printj";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/printj/-/printj-1.1.2.tgz";
        sha512 = "zA2SmoLaxZyArQTOPj5LXecR+RagfPSU5Kw1qP+jkWeNlrq+eJZyY2oS68SU1Z/7/myXM4lo9716laOFAVStCQ==";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "nolQXZ/4L+bP/UGlkfaIujX9BKxGwmQ9OT4mOt5yvy8iK1h3wqTEJCijzGANTCCl9nWjY41juyAn2K3Q1hLLTg==";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "prop-types-15.8.1" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.8.1.tgz";
        sha512 = "oj87CgZICdulUohogVAR7AjlC0327U4el4L6eAvOqCeudMDVU0NThNaV+b9Df4dXgSP1gXMTnPdhfe/2qDH5cg==";
      };
    };
    "prop-types-extra-1.1.0" = {
      name = "prop-types-extra";
      packageName = "prop-types-extra";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types-extra/-/prop-types-extra-1.1.0.tgz";
        sha512 = "QFyuDxvMipmIVKD2TwxLVPzMnO4e5oOf1vr3tJIomL8E7d0lr6phTHd5nkPhFIzTD1idBLLEPeylL9g+rrTzRg==";
      };
    };
    "queue-6.0.1" = {
      name = "queue";
      packageName = "queue";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue/-/queue-6.0.1.tgz";
        sha512 = "AJBQabRCCNr9ANq8v77RJEv73DPbn55cdTb+Giq4X0AVnNVZvMHlYp7XlQiN+1npCZj1DuSmaA2hYVUUDgxFDg==";
      };
    };
    "raf-3.4.1" = {
      name = "raf";
      packageName = "raf";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/raf/-/raf-3.4.1.tgz";
        sha512 = "Sq4CW4QhwOHE8ucn6J34MqtZCeWFP2aQSmrlroYgqAV1PjStIhJXxYuTgUIfkEk7zTLjmIjLmU5q+fbD1NnOJA==";
      };
    };
    "raf-schd-2.1.2" = {
      name = "raf-schd";
      packageName = "raf-schd";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raf-schd/-/raf-schd-2.1.2.tgz";
        sha512 = "Orl0IEvMtUCgPddgSxtxreK77UiQz4nPYJy9RggVzu4mKsZkQWiAaG1y9HlYWdvm9xtN348xRaT37qkvL/+A+g==";
      };
    };
    "react-16.13.1" = {
      name = "react";
      packageName = "react";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.13.1.tgz";
        sha512 = "YMZQQq32xHLX0bz5Mnibv1/LHb3Sqzngu7xstSM+vrkE5Kzr9xE0yMByK5kMoTK30YVJE61WfbxIFFvfeDKT1w==";
      };
    };
    "react-alert-7.0.3" = {
      name = "react-alert";
      packageName = "react-alert";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-alert/-/react-alert-7.0.3.tgz";
        sha512 = "cZ2ZhxytECTxljDfBKpQmwWbfJQFzFf2Qf03L/IB5shbEXtWhDD2JjiW60rwmKT1oZoU+GEnUQw5MFM5+f0B6A==";
      };
    };
    "react-alert-template-basic-1.0.2" = {
      name = "react-alert-template-basic";
      packageName = "react-alert-template-basic";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-alert-template-basic/-/react-alert-template-basic-1.0.2.tgz";
        sha512 = "nJSIknM5xN/GzKdKkb5/X9zdiLxSqctww3mEouyeR891nUGP8guqFpCGD8vCjFYSZtq8z3tGcAKBG1XjtLHFHQ==";
      };
    };
    "react-bootstrap-0.33.1" = {
      name = "react-bootstrap";
      packageName = "react-bootstrap";
      version = "0.33.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-bootstrap/-/react-bootstrap-0.33.1.tgz";
        sha512 = "qWTRravSds87P8WC82tETy2yIso8qDqlIm0czsrduCaYAFtHuyLu0XDbUlfLXeRzqgwm5sRk2wRaTNoiVkk/YQ==";
      };
    };
    "react-bootstrap-typeahead-4.2.3" = {
      name = "react-bootstrap-typeahead";
      packageName = "react-bootstrap-typeahead";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-bootstrap-typeahead/-/react-bootstrap-typeahead-4.2.3.tgz";
        sha512 = "qDMql6I+x5oU+Ek90B90763zL9EHYv6hcShEtobuyofgHOuAiMB8HNA4Zlt4JCbL/5bbM4+bnSAc9c5a6cQ6kg==";
      };
    };
    "react-clientside-effect-1.2.2" = {
      name = "react-clientside-effect";
      packageName = "react-clientside-effect";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-clientside-effect/-/react-clientside-effect-1.2.2.tgz";
        sha512 = "nRmoyxeok5PBO6ytPvSjKp9xwXg9xagoTK1mMjwnQxqM9Hd7MNPl+LS1bOSOe+CV2+4fnEquc7H/S8QD3q697A==";
      };
    };
    "react-context-toolbox-2.0.2" = {
      name = "react-context-toolbox";
      packageName = "react-context-toolbox";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-context-toolbox/-/react-context-toolbox-2.0.2.tgz";
        sha512 = "tY4j0imkYC3n5ZlYSgFkaw7fmlCp3IoQQ6DxpqeNHzcD0hf+6V+/HeJxviLUZ1Rv1Yn3N3xyO2EhkkZwHn0m1A==";
      };
    };
    "react-dom-16.13.1" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.13.1.tgz";
        sha512 = "81PIMmVLnCNLO/fFOQxdQkvEq/+Hfpv24XNJfpyZhTRfO0QcmQIF/PgCa1zCOj2w1hrn12MFLyaJ/G0+Mxtfag==";
      };
    };
    "react-focus-lock-2.4.1" = {
      name = "react-focus-lock";
      packageName = "react-focus-lock";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-focus-lock/-/react-focus-lock-2.4.1.tgz";
        sha512 = "c5ZP56KSpj9EAxzScTqQO7bQQNPltf/W1ZEBDqNDOV1XOIwvAyHX0O7db9ekiAtxyKgnqZjQlLppVg94fUeL9w==";
      };
    };
    "react-focus-on-3.4.1" = {
      name = "react-focus-on";
      packageName = "react-focus-on";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-focus-on/-/react-focus-on-3.4.1.tgz";
        sha512 = "KGRIl0iAu+1k1dcX7eQCXF5ZR/nl+XyXN5Ukw/OY80vLaK2b6vDzNqnX0HdYbY5xSUhIRUvMWEzSsdEyPjvk/Q==";
      };
    };
    "react-full-screen-0.2.5" = {
      name = "react-full-screen";
      packageName = "react-full-screen";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-full-screen/-/react-full-screen-0.2.5.tgz";
        sha512 = "LNkxjLWmiR+AwemSVdn/miUcBy8tHA6mDVS1qz1AM/DHNEtQbzkh5ok9A6g99502OqutQq1zBvCBGLV8rsB2tw==";
      };
    };
    "react-if-4.1.4" = {
      name = "react-if";
      packageName = "react-if";
      version = "4.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-if/-/react-if-4.1.4.tgz";
        sha512 = "bjufPfCdPBiBy9EO/BeoxaqGc/xCwTu0coKtHfjpJw+v85DLMbpG43IUPISh+m3DzENx1rOYLpqbp2KaDmEYlg==";
      };
    };
    "react-images-1.1.7" = {
      name = "react-images";
      packageName = "react-images";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-images/-/react-images-1.1.7.tgz";
        sha512 = "9paR4bdP/SPTbJ/8cLa6+7+pcq8PGN4/8UjTfztQKBRzGxH0BtHrB7oj/7As2RmYMkOsVIMNfDaWzZZK4faIRA==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "react-is-16.8.6" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.8.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.8.6.tgz";
        sha512 = "aUk3bHfZ2bRSVFFbbeVS4i+lNPZr3/WM5jT2J5omUVV1zzcs1nAaf3l51ctA5FFvCRbhrH0bdAsRRQddFJZPtA==";
      };
    };
    "react-lifecycles-compat-3.0.4" = {
      name = "react-lifecycles-compat";
      packageName = "react-lifecycles-compat";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-lifecycles-compat/-/react-lifecycles-compat-3.0.4.tgz";
        sha512 = "fBASbA6LnOU9dOU2eW7aQ8xmYBSXUIWr+UmF9b1efZBazGNO+rcXT/icdKnYm2pTwcRylVUYwW7H1PHfLekVzA==";
      };
    };
    "react-motion-0.5.2" = {
      name = "react-motion";
      packageName = "react-motion";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-motion/-/react-motion-0.5.2.tgz";
        sha512 = "9q3YAvHoUiWlP3cK0v+w1N5Z23HXMj4IF4YuvjvWegWqNPfLXsOBE/V7UvQGpXxHFKRQQcNcVQE31g9SB/6qgQ==";
      };
    };
    "react-overlays-0.9.2" = {
      name = "react-overlays";
      packageName = "react-overlays";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-overlays/-/react-overlays-0.9.2.tgz";
        sha512 = "wOi+WqO0acnUAMCbTTW06/GRkYjHdlvIoyX4bYkLvxKrLgl2kX9WzFVyBdwukl2jvN7I7oX7ZXAz7MNOWYdgCA==";
      };
    };
    "react-overlays-1.2.0" = {
      name = "react-overlays";
      packageName = "react-overlays";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-overlays/-/react-overlays-1.2.0.tgz";
        sha512 = "i/FCV8wR6aRaI+Kz/dpJhOdyx+ah2tN1RhT9InPrexyC4uzf3N4bNayFTGtUeQVacj57j1Mqh1CwV60/5153Iw==";
      };
    };
    "react-photo-gallery-8.0.0" = {
      name = "react-photo-gallery";
      packageName = "react-photo-gallery";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-photo-gallery/-/react-photo-gallery-8.0.0.tgz";
        sha512 = "Y9458yygEB9cIZAWlBWuenlR+ghin1RopmmU3Vice8BeJl0Se7hzfxGDq8W1armB/ic/kphGg+G1jq5fOEd0sw==";
      };
    };
    "react-popper-1.3.7" = {
      name = "react-popper";
      packageName = "react-popper";
      version = "1.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-popper/-/react-popper-1.3.7.tgz";
        sha512 = "nmqYTx7QVjCm3WUZLeuOomna138R1luC4EqkW3hxJUrAe+3eNz3oFCLYdnPwILfn0mX1Ew2c3wctrjlUMYYUww==";
      };
    };
    "react-prop-types-0.4.0" = {
      name = "react-prop-types";
      packageName = "react-prop-types";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-prop-types/-/react-prop-types-0.4.0.tgz";
        sha1 = "f99b0bfb4006929c9af2051e7c1414a5c75b93d0";
      };
    };
    "react-property-1.0.1" = {
      name = "react-property";
      packageName = "react-property";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-property/-/react-property-1.0.1.tgz";
        sha512 = "1tKOwxFn3dXVomH6pM9IkLkq2Y8oh+fh/lYW3MJ/B03URswUTqttgckOlbxY2XHF3vPG6uanSc4dVsLW/wk3wQ==";
      };
    };
    "react-remove-scroll-2.3.0" = {
      name = "react-remove-scroll";
      packageName = "react-remove-scroll";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-remove-scroll/-/react-remove-scroll-2.3.0.tgz";
        sha512 = "UqVimLeAe+5EHXKfsca081hAkzg3WuDmoT9cayjBegd6UZVhlTEchleNp9J4TMGkb/ftLve7ARB5Wph+HJ7A5g==";
      };
    };
    "react-remove-scroll-bar-2.1.0" = {
      name = "react-remove-scroll-bar";
      packageName = "react-remove-scroll-bar";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-remove-scroll-bar/-/react-remove-scroll-bar-2.1.0.tgz";
        sha512 = "5X5Y5YIPjIPrAoMJxf6Pfa7RLNGCgwZ95TdnVPgPuMftRfO8DaC7F4KP1b5eiO8hHbe7u+wZNDbYN5WUTpv7+g==";
      };
    };
    "react-style-singleton-2.1.0" = {
      name = "react-style-singleton";
      packageName = "react-style-singleton";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-style-singleton/-/react-style-singleton-2.1.0.tgz";
        sha512 = "DH4ED+YABC1dhvSDYGGreAHmfuTXj6+ezT3CmHoqIEfxNgEYfIMoOtmbRp42JsUst3IPqBTDL+8r4TF7EWhIHw==";
      };
    };
    "react-transition-group-2.9.0" = {
      name = "react-transition-group";
      packageName = "react-transition-group";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-transition-group/-/react-transition-group-2.9.0.tgz";
        sha512 = "+HzNTCHpeQyl4MJ/bdE0u6XRMe9+XG/+aL4mCxVN4DnPBQ0/5bfHWPDuOZUzYdMj94daZaZdCCc1Dzt9R/xSSg==";
      };
    };
    "react-transition-group-4.4.2" = {
      name = "react-transition-group";
      packageName = "react-transition-group";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-transition-group/-/react-transition-group-4.4.2.tgz";
        sha512 = "/RNYfRAMlZwDSr6z4zNKV6xu53/e2BuaBbGhbyYIXTrmgu/bGHzmqOs7mJSJBHy9Ud+ApHx3QjrkKSp1pxvlFg==";
      };
    };
    "react-view-pager-0.6.0" = {
      name = "react-view-pager";
      packageName = "react-view-pager";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-view-pager/-/react-view-pager-0.6.0.tgz";
        sha512 = "nV6VTLyHmv4T9QszZVD3sRn3EcUKgb2NhSdz9kjTIpzE+SwOl4mfcQtqUwc6St3EnMtus805zVJ8OcSjFEqhpg==";
      };
    };
    "readable-stream-3.4.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.4.0.tgz";
        sha512 = "jItXPLmrSR8jmTRmRWJXCnGJsfy85mB3Wd/uINMXA65yrnFo0cPClFIUWzo2najVNSl+mx7/4W8ttlLWJe99pQ==";
      };
    };
    "regenerator-runtime-0.13.9" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.9.tgz";
        sha512 = "p3VT+cOEgxFsRRA9X4lkI1E+k2/CtnKtU4gcxyaCUreilL/vqI6CdZ3wxVUx3UOUg+gnUOQQcRI7BmSI656MYA==";
      };
    };
    "regexp.prototype.flags-1.4.3" = {
      name = "regexp.prototype.flags";
      packageName = "regexp.prototype.flags";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp.prototype.flags/-/regexp.prototype.flags-1.4.3.tgz";
        sha512 = "fjggEOO3slI6Wvgjwflkc4NFRCTZAu5CnNfBd5qOMYhWdn67nJBBu34/TkD++eeFmd8C9r9jfXJ27+nSiRkSUA==";
      };
    };
    "resize-observer-polyfill-1.5.0" = {
      name = "resize-observer-polyfill";
      packageName = "resize-observer-polyfill";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resize-observer-polyfill/-/resize-observer-polyfill-1.5.0.tgz";
        sha512 = "M2AelyJDVR/oLnToJLtuDJRBBWUGUvvGigj1411hXhAdyFWqMaqHp7TixW3FpiLuVaikIcR1QL+zqoJoZlOgpg==";
      };
    };
    "resize-observer-polyfill-1.5.1" = {
      name = "resize-observer-polyfill";
      packageName = "resize-observer-polyfill";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resize-observer-polyfill/-/resize-observer-polyfill-1.5.1.tgz";
        sha512 = "LwZrotdHOo12nQuZlHEmtuXdqGoOD0OhaxopaNFxWzInpEgaLWoVuAMbTzixuosCx2nEG58ngzW3vxdWoxIgdg==";
      };
    };
    "rxjs-6.6.7" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "6.6.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-6.6.7.tgz";
        sha512 = "hTdwr+7yYNIT5n4AMYp85KA6yw2Va0FLa3Rguvbpa4W3I5xynaBZo41cM3XM+4Q6fRMj3sBYIR1VAmZMXYJvRQ==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sanitize-filename-1.6.3" = {
      name = "sanitize-filename";
      packageName = "sanitize-filename";
      version = "1.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanitize-filename/-/sanitize-filename-1.6.3.tgz";
        sha512 = "y/52Mcy7aw3gRm7IrcGDFx/bCk4AhRh2eI9luHOQM86nZsqwiRkkq2GekHXBBD+SmPidc8i2PqtYZl+pWJ8Oeg==";
      };
    };
    "scheduler-0.19.1" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.19.1.tgz";
        sha512 = "n/zwRWRYSUj0/3g/otKDRPMh6qv2SYMWNq85IEa8iZyAv8od9zDYpGSnpBEjNgcMNq6Scbu5KfIPxNF72R/2EA==";
      };
    };
    "scroll-into-view-if-needed-2.2.26" = {
      name = "scroll-into-view-if-needed";
      packageName = "scroll-into-view-if-needed";
      version = "2.2.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/scroll-into-view-if-needed/-/scroll-into-view-if-needed-2.2.26.tgz";
        sha512 = "SQ6AOKfABaSchokAmmaxVnL9IArxEnLEX9j4wAZw+x4iUTb40q7irtHG3z4GtAWz5veVZcCnubXDBRyLVQaohw==";
      };
    };
    "semver-7.3.7" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.7.tgz";
        sha512 = "QlYTucUYOews+WeEujDoEGziz4K6c47V/Bd+LjSSYcA94p+DmINdf7ncaUinThfvZyu13lN9OY1XDxt8C0Tw0g==";
      };
    };
    "setimmediate-1.0.5" = {
      name = "setimmediate";
      packageName = "setimmediate";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/setimmediate/-/setimmediate-1.0.5.tgz";
        sha1 = "290cbb232e306942d7d7ea9b83732ab7856f8285";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "side-channel-1.0.4" = {
      name = "side-channel";
      packageName = "side-channel";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel/-/side-channel-1.0.4.tgz";
        sha512 = "q5XPytqFEIKHkGdiMIrY10mvLRvnQh42/+GoBlFW3b2LXLE2xxJpZFdm94we0BaoV3RwJyGqg5wS7epxTv0Zvw==";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "ssf-0.8.2" = {
      name = "ssf";
      packageName = "ssf";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ssf/-/ssf-0.8.2.tgz";
        sha1 = "b9d4dc6a1c1bcf76f8abfa96d7d7656fb2abecd6";
      };
    };
    "stream-chain-2.2.5" = {
      name = "stream-chain";
      packageName = "stream-chain";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-chain/-/stream-chain-2.2.5.tgz";
        sha512 = "1TJmBx6aSWqZ4tx7aTpBDXK0/e2hhcNSTV8+CbFJtDjbb+I1mZ8lHit0Grw9GRT+6JbIrrDd8esncgBi8aBXGA==";
      };
    };
    "stream-json-1.7.4" = {
      name = "stream-json";
      packageName = "stream-json";
      version = "1.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-json/-/stream-json-1.7.4.tgz";
        sha512 = "ja2dde1v7dOlx5/vmavn8kLrxvNfs7r2oNc5DYmNJzayDDdudyCSuTB1gFjH4XBVTIwxiMxL4i059HX+ZiouXg==";
      };
    };
    "string.prototype.trimend-1.0.5" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.5.tgz";
        sha512 = "I7RGvmjV4pJ7O3kdf+LXFpVfdNOxtCW/2C8f6jNiW4+PQchwxkCDzlk1/7p+Wl4bqFIZeF47qAHXLuHHWKAxog==";
      };
    };
    "string.prototype.trimstart-1.0.5" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.5.tgz";
        sha512 = "THx16TJCGlsN0o6dl2o6ncWUsdgnLRSA23rRE5pyGBw/mLr3Ej/R2LaqCtgP8VNMGZsvMWnf9ooZPyY2bHvUFg==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "style-to-object-0.3.0" = {
      name = "style-to-object";
      packageName = "style-to-object";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/style-to-object/-/style-to-object-0.3.0.tgz";
        sha512 = "CzFnRRXhzWIdItT3OmF8SQfWyahHhjq3HwcMNCNLn+N7klOOqPjMeG/4JSu77D7ypZdGvSzvkrbyeTMizz2VrA==";
      };
    };
    "style-value-types-3.1.7" = {
      name = "style-value-types";
      packageName = "style-value-types";
      version = "3.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/style-value-types/-/style-value-types-3.1.7.tgz";
        sha512 = "jPaG5HcAPs3vetSwOJozrBXxuHo9tjZVnbRyBjxqb00c2saIoeuBJc1/2MtvB8eRZy41u/BBDH0CpfzWixftKg==";
      };
    };
    "stylefire-7.0.3" = {
      name = "stylefire";
      packageName = "stylefire";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylefire/-/stylefire-7.0.3.tgz";
        sha512 = "Q0l7NSeFz/OkX+o6/7Zg3VZxSAZeQzQpYomWmIpOehFM/rJNMSLVX5fgg6Q48ut2ETNKwdhm97mPNU643EBCoQ==";
      };
    };
    "tabbable-1.1.2" = {
      name = "tabbable";
      packageName = "tabbable";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tabbable/-/tabbable-1.1.2.tgz";
        sha512 = "77oqsKEPrxIwgRcXUwipkj9W5ItO97L6eUT1Ar7vh+El16Zm4M6V+YU1cbipHEa6q0Yjw8O3Hoh8oRgatV5s7A==";
      };
    };
    "truncate-utf8-bytes-1.0.2" = {
      name = "truncate-utf8-bytes";
      packageName = "truncate-utf8-bytes";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/truncate-utf8-bytes/-/truncate-utf8-bytes-1.0.2.tgz";
        sha1 = "405923909592d56f78a5818434b0b78489ca5f2b";
      };
    };
    "tslib-1.10.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.10.0.tgz";
        sha512 = "qOebF53frne81cf0S9B41ByenJ3/IuH8yJKngAX35CmiZySA0khhkovshKK+jGCaMnVomla7gVlIcc3EvKPbTQ==";
      };
    };
    "typed-styles-0.0.7" = {
      name = "typed-styles";
      packageName = "typed-styles";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/typed-styles/-/typed-styles-0.0.7.tgz";
        sha512 = "pzP0PWoZUhsECYjABgCGQlRGL1n7tOHsgwYv3oIiEpJwGhFTuty/YNeduxQYzXXa3Ge5BdT6sHYIQYpl4uJ+5Q==";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "ua-parser-js-0.7.31" = {
      name = "ua-parser-js";
      packageName = "ua-parser-js";
      version = "0.7.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.31.tgz";
        sha512 = "qLK/Xe9E2uzmYI3qLeOmI0tEOt+TBBQyUIAh4aAgU05FVYzeZrKUdkAZfBNVGRaHVgV0TDkdEngJSw/SyQchkQ==";
      };
    };
    "unbox-primitive-1.0.2" = {
      name = "unbox-primitive";
      packageName = "unbox-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unbox-primitive/-/unbox-primitive-1.0.2.tgz";
        sha512 = "61pPlCD9h51VoreyJ0BReideM3MDKMKnh6+V9L08331ipq6Q8OFXZYiqP6n/tbHx4s5I9uRhcye6BrbkizkBDw==";
      };
    };
    "uncontrollable-6.2.3" = {
      name = "uncontrollable";
      packageName = "uncontrollable";
      version = "6.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uncontrollable/-/uncontrollable-6.2.3.tgz";
        sha512 = "VgOAoBU2ptCL2bfTG2Mra0I8i1u6Aq84AFonD5tmCAYSfs3hWvr2Rlw0q2ntoxXTHjcQOmZOh3FKaN+UZVyREQ==";
      };
    };
    "uncontrollable-7.1.1" = {
      name = "uncontrollable";
      packageName = "uncontrollable";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uncontrollable/-/uncontrollable-7.1.1.tgz";
        sha512 = "EcPYhot3uWTS3w00R32R2+vS8Vr53tttrvMj/yA1uYRhf8hbTG2GyugGqWDY0qIskxn0uTTojVd6wPYW9ZEf8Q==";
      };
    };
    "use-callback-ref-1.2.4" = {
      name = "use-callback-ref";
      packageName = "use-callback-ref";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/use-callback-ref/-/use-callback-ref-1.2.4.tgz";
        sha512 = "rXpsyvOnqdScyied4Uglsp14qzag1JIemLeTWGKbwpotWht57hbP78aNT+Q4wdFKQfQibbUX4fb6Qb4y11aVOQ==";
      };
    };
    "use-sidecar-1.0.2" = {
      name = "use-sidecar";
      packageName = "use-sidecar";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/use-sidecar/-/use-sidecar-1.0.2.tgz";
        sha512 = "287RZny6m5KNMTb/Kq9gmjafi7lQL0YHO1lYolU6+tY1h9+Z3uCtkJJ3OSOq3INwYf2hBryCcDh4520AhJibMA==";
      };
    };
    "utf8-byte-length-1.0.4" = {
      name = "utf8-byte-length";
      packageName = "utf8-byte-length";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf8-byte-length/-/utf8-byte-length-1.0.4.tgz";
        sha1 = "f45f150c4c66eee968186505ab93fcbb8ad6bf61";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "uuid-8.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "8.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-8.3.2.tgz";
        sha512 = "+NYs2QeMWy+GWFOEm9xnn6HCDp0l7QBD7ml8zLUmJ+93Q5NF0NocErnwkTkXVFNiX3/fpC6afS8Dhb/gz7R7eg==";
      };
    };
    "voc-1.1.0" = {
      name = "voc";
      packageName = "voc";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/voc/-/voc-1.1.0.tgz";
        sha512 = "fthgd8OJLqq8vPcLjElTk6Rcl2e3v5ekcXauImaqEnQqd5yUWKg1+ZOBgS2KTWuVKcuvZMQq4TDptiT1uYddUA==";
      };
    };
    "warning-3.0.0" = {
      name = "warning";
      packageName = "warning";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-3.0.0.tgz";
        sha1 = "32e5377cb572de4ab04753bdf8821c01ed605b7c";
      };
    };
    "warning-4.0.3" = {
      name = "warning";
      packageName = "warning";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-4.0.3.tgz";
        sha512 = "rpJyN222KWIvHJ/F53XSZv0Zl/accqHR8et1kpaMTD/fLCRxtV8iX8czMzY7sVZupTI3zcUTg8eycS2kNF9l6w==";
      };
    };
    "whatwg-fetch-3.2.0" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-3.2.0.tgz";
        sha512 = "SdGPoQMMnzVYThUbSrEvqTlkvC1Ux27NehaJ/GUHBfNrh5Mjg+1/uRyFMwVnxO2MrikMWvWAqUGgQOfVU4hT7w==";
      };
    };
    "which-2.0.1" = {
      name = "which";
      packageName = "which";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.1.tgz";
        sha512 = "N7GBZOTswtB9lkQBZA4+zAXrjEIWAUOB93AvzUiudRzRxhUdLURQ7D/gAIMY1gatT/LTbmbcv8SiYazy3eYB7w==";
      };
    };
    "which-boxed-primitive-1.0.2" = {
      name = "which-boxed-primitive";
      packageName = "which-boxed-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz";
        sha512 = "bwZdv0AKLpplFY2KZRX6TvyuN7ojjr7lwkg6ml0roIy9YeuSr7JS372qlNW18UQYzgYK9ziGcerWqZOmEn9VNg==";
      };
    };
    "write-file-atomic-2.4.3" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-2.4.3.tgz";
        sha512 = "GaETH5wwsX+GcnzhPgKcKjJ6M2Cq3/iZp1WyY/X1CSqrW+jVNM9Y7D8EC2sM4ZG/V8wZlSniJnCKWPmBYAucRQ==";
      };
    };
    "xlsx-0.7.12" = {
      name = "xlsx";
      packageName = "xlsx";
      version = "0.7.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/xlsx/-/xlsx-0.7.12.tgz";
        sha512 = "+dljNu2OdnbvAsjWZPlB4YMsJjC0JcNeR0cYH5lowp2YrxF55HjgD0jcff9alUDHxEKGw0nLIlbd9K+QbteEgg==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
  args = {
    name = "bloodhound";
    packageName = "bloodhound";
    version = "4.2.0";
    src = ./.;
    dependencies = [
      sources."@babel/runtime-7.18.3"
      (sources."@babel/runtime-corejs2-7.11.2" // {
        dependencies = [
          sources."core-js-2.6.12"
        ];
      })
      sources."@emotion/is-prop-valid-0.8.8"
      sources."@emotion/memoize-0.7.4"
      sources."@fortawesome/fontawesome-free-6.1.1"
      sources."@popmotion/easing-1.0.2"
      sources."@popmotion/popcorn-0.4.4"
      sources."@types/domhandler-2.4.1"
      sources."@types/prop-types-15.7.3"
      sources."@types/react-16.9.43"
      sources."a11y-focus-store-1.0.0"
      sources."adler-32-1.2.0"
      sources."adm-zip-0.5.9"
      sources."animation-bus-0.2.0"
      sources."aria-hidden-1.1.1"
      sources."asap-2.0.6"
      sources."base64-js-1.3.1"
      sources."bootstrap-3.4.1"
      sources."bowser-1.9.4"
      sources."buffer-from-1.1.1"
      sources."call-bind-1.0.2"
      sources."cfb-1.1.0"
      sources."classnames-2.2.6"
      sources."clsx-1.2.1"
      sources."codepage-1.3.8"
      sources."colors-0.6.2"
      sources."commander-2.20.0"
      sources."compute-scroll-into-view-1.0.16"
      sources."concat-stream-2.0.0"
      sources."conf-1.4.0"
      sources."crc-32-1.2.0"
      (sources."create-react-context-0.3.0" // {
        dependencies = [
          sources."warning-4.0.3"
        ];
      })
      (sources."cross-env-7.0.3" // {
        dependencies = [
          sources."cross-spawn-7.0.1"
          sources."path-key-3.1.0"
          sources."shebang-command-2.0.0"
          sources."shebang-regex-3.0.0"
          sources."which-2.0.1"
        ];
      })
      sources."css-in-js-utils-2.0.1"
      sources."csstype-2.6.11"
      sources."dagre-0.8.5"
      sources."deep-equal-1.1.1"
      sources."define-properties-1.1.4"
      sources."detect-node-2.0.4"
      sources."dom-helpers-3.4.0"
      (sources."dom-serializer-0.2.2" // {
        dependencies = [
          sources."domelementtype-2.0.1"
          sources."entities-2.0.3"
        ];
      })
      sources."domelementtype-1.3.1"
      sources."domhandler-2.4.2"
      sources."domutils-1.7.0"
      sources."dot-prop-4.2.1"
      sources."electron-store-1.3.0"
      (sources."encoding-0.1.13" // {
        dependencies = [
          sources."iconv-lite-0.6.2"
        ];
      })
      sources."entities-1.1.2"
      sources."env-paths-1.0.0"
      sources."es-abstract-1.20.1"
      sources."es-to-primitive-1.2.1"
      sources."eventemitter2-6.4.6"
      sources."exit-on-epipe-1.0.1"
      sources."fast-deep-equal-3.1.3"
      (sources."fbjs-0.8.18" // {
        dependencies = [
          sources."core-js-1.2.7"
        ];
      })
      sources."file-type-10.11.0"
      sources."find-up-2.1.0"
      sources."focus-lock-0.7.0"
      sources."fontfaceobserver-2.3.0"
      sources."frac-0.3.1"
      sources."framer-motion-1.11.1"
      sources."framesync-4.0.4"
      sources."fscreen-1.0.2"
      sources."function-bind-1.1.1"
      sources."function.prototype.name-1.1.5"
      sources."functions-have-names-1.2.3"
      sources."get-intrinsic-1.1.1"
      sources."get-nonce-1.0.1"
      sources."get-prefix-1.0.0"
      sources."get-symbol-description-1.0.0"
      sources."glam-5.0.1"
      sources."graceful-fs-4.1.15"
      sources."graphlib-2.1.8"
      sources."gud-1.0.0"
      sources."has-1.0.3"
      sources."has-bigints-1.0.2"
      sources."has-property-descriptors-1.0.0"
      sources."has-symbols-1.0.3"
      sources."has-tostringtag-1.0.0"
      sources."he-1.2.0"
      sources."hey-listen-1.0.8"
      sources."html-dom-parser-0.2.3"
      sources."html-react-parser-0.10.5"
      sources."htmlparser2-3.10.1"
      sources."hyphenate-style-name-1.0.4"
      sources."ieee754-1.2.1"
      sources."image-size-0.8.3"
      sources."image-type-4.1.0"
      sources."imurmurhash-0.1.4"
      sources."inherits-2.0.3"
      sources."inline-style-parser-0.1.1"
      sources."inline-style-prefixer-3.0.8"
      sources."internal-slot-1.0.3"
      sources."invariant-2.2.4"
      sources."is-arguments-1.0.4"
      sources."is-bigint-1.0.4"
      sources."is-boolean-object-1.1.2"
      sources."is-callable-1.2.4"
      sources."is-date-object-1.0.2"
      sources."is-negative-zero-2.0.2"
      sources."is-number-object-1.0.7"
      sources."is-obj-1.0.1"
      sources."is-regex-1.1.4"
      sources."is-shared-array-buffer-1.0.2"
      sources."is-stream-1.1.0"
      sources."is-string-1.0.7"
      sources."is-symbol-1.0.3"
      sources."is-weakref-1.0.2"
      sources."is-zip-file-1.0.2"
      sources."isexe-2.0.0"
      sources."isobject-3.0.1"
      sources."isomorphic-fetch-2.2.1"
      sources."jquery-3.6.0"
      sources."js-tokens-4.0.0"
      sources."jszip-2.4.0"
      sources."keycode-2.2.0"
      (sources."linkurious-1.5.2" // {
        dependencies = [
          sources."dagre-0.7.4"
          sources."graphlib-1.0.7"
          sources."lodash-3.10.1"
        ];
      })
      sources."locate-path-2.0.0"
      sources."lodash-4.17.21"
      sources."lodash.debounce-4.0.8"
      sources."loose-envify-1.4.0"
      sources."make-dir-1.3.0"
      sources."md5-file-4.0.0"
      sources."mitt-1.1.3"
      sources."mustache-2.3.2"
      sources."neo4j-driver-4.4.6"
      (sources."neo4j-driver-bolt-connection-4.4.6" // {
        dependencies = [
          sources."buffer-6.0.3"
        ];
      })
      sources."neo4j-driver-core-4.4.6"
      sources."node-fetch-1.7.3"
      sources."node-ratify-1.1.32"
      sources."object-assign-4.1.1"
      sources."object-inspect-1.12.0"
      sources."object-is-1.1.2"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.2"
      sources."p-limit-1.3.0"
      sources."p-locate-2.0.0"
      sources."p-try-1.0.0"
      sources."pako-0.2.9"
      sources."path-exists-3.0.0"
      sources."performance-now-0.2.0"
      sources."pify-3.0.0"
      sources."pkg-up-2.0.0"
      sources."popmotion-9.0.0-beta-8"
      sources."popper.js-1.16.1"
      sources."printj-1.1.2"
      sources."promise-7.3.1"
      (sources."prop-types-15.8.1" // {
        dependencies = [
          sources."react-is-16.13.1"
        ];
      })
      sources."prop-types-extra-1.1.0"
      sources."queue-6.0.1"
      (sources."raf-3.4.1" // {
        dependencies = [
          sources."performance-now-2.1.0"
        ];
      })
      sources."raf-schd-2.1.2"
      sources."react-16.13.1"
      sources."react-alert-7.0.3"
      sources."react-alert-template-basic-1.0.2"
      (sources."react-bootstrap-0.33.1" // {
        dependencies = [
          sources."react-overlays-0.9.2"
          sources."react-transition-group-2.9.0"
        ];
      })
      (sources."react-bootstrap-typeahead-4.2.3" // {
        dependencies = [
          sources."warning-4.0.3"
        ];
      })
      sources."react-clientside-effect-1.2.2"
      sources."react-context-toolbox-2.0.2"
      sources."react-dom-16.13.1"
      sources."react-focus-lock-2.4.1"
      sources."react-focus-on-3.4.1"
      sources."react-full-screen-0.2.5"
      sources."react-if-4.1.4"
      (sources."react-images-1.1.7" // {
        dependencies = [
          sources."react-transition-group-2.9.0"
        ];
      })
      sources."react-is-16.8.6"
      sources."react-lifecycles-compat-3.0.4"
      sources."react-motion-0.5.2"
      (sources."react-overlays-1.2.0" // {
        dependencies = [
          sources."uncontrollable-6.2.3"
          sources."warning-4.0.3"
        ];
      })
      (sources."react-photo-gallery-8.0.0" // {
        dependencies = [
          sources."prop-types-15.7.2"
        ];
      })
      (sources."react-popper-1.3.7" // {
        dependencies = [
          sources."warning-4.0.3"
        ];
      })
      sources."react-prop-types-0.4.0"
      sources."react-property-1.0.1"
      sources."react-remove-scroll-2.3.0"
      sources."react-remove-scroll-bar-2.1.0"
      sources."react-style-singleton-2.1.0"
      (sources."react-transition-group-4.4.2" // {
        dependencies = [
          sources."csstype-3.0.10"
          sources."dom-helpers-5.2.1"
        ];
      })
      (sources."react-view-pager-0.6.0" // {
        dependencies = [
          sources."resize-observer-polyfill-1.5.0"
        ];
      })
      sources."readable-stream-3.4.0"
      sources."regenerator-runtime-0.13.9"
      sources."regexp.prototype.flags-1.4.3"
      sources."resize-observer-polyfill-1.5.1"
      sources."rxjs-6.6.7"
      sources."safer-buffer-2.1.2"
      sources."sanitize-filename-1.6.3"
      sources."scheduler-0.19.1"
      sources."scroll-into-view-if-needed-2.2.26"
      (sources."semver-7.3.7" // {
        dependencies = [
          sources."lru-cache-6.0.0"
          sources."yallist-4.0.0"
        ];
      })
      sources."setimmediate-1.0.5"
      sources."side-channel-1.0.4"
      sources."signal-exit-3.0.2"
      sources."ssf-0.8.2"
      sources."stream-chain-2.2.5"
      sources."stream-json-1.7.4"
      sources."string.prototype.trimend-1.0.5"
      sources."string.prototype.trimstart-1.0.5"
      (sources."string_decoder-1.3.0" // {
        dependencies = [
          sources."safe-buffer-5.2.1"
        ];
      })
      sources."style-to-object-0.3.0"
      sources."style-value-types-3.1.7"
      sources."stylefire-7.0.3"
      sources."tabbable-1.1.2"
      sources."truncate-utf8-bytes-1.0.2"
      sources."tslib-1.10.0"
      sources."typed-styles-0.0.7"
      sources."typedarray-0.0.6"
      sources."ua-parser-js-0.7.31"
      sources."unbox-primitive-1.0.2"
      sources."uncontrollable-7.1.1"
      sources."use-callback-ref-1.2.4"
      sources."use-sidecar-1.0.2"
      sources."utf8-byte-length-1.0.4"
      sources."util-deprecate-1.0.2"
      sources."uuid-8.3.2"
      sources."voc-1.1.0"
      sources."warning-3.0.0"
      sources."whatwg-fetch-3.2.0"
      sources."which-boxed-primitive-1.0.2"
      sources."write-file-atomic-2.4.3"
      sources."xlsx-0.7.12"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Graph Theory for Active Directory";
      homepage = "https://github.com/BloodHoundAD/Bloodhound";
      license = "GPL-3.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
